package liquidacionautomatica;

import io.opentelemetry.api.internal.StringUtils;
import liquidacionautomatica.entities.*;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.*;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;

/**
 * @author rbayarri
 */
public class LiquidacionJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LiquidacionJFrame
     */
    private User user;
    private String directory;
    private File file;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountUntil2;
    private javax.swing.JButton cancel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton liquidar;
    private javax.swing.JComboBox<String> typeLiquidacion;

    public LiquidacionJFrame() {
    }

    public LiquidacionJFrame(User user, String amountUntil2) {
        initComponents();
        this.typeLiquidacion.addItem("Contratos");
        this.typeLiquidacion.addItem("Incentivos");
        this.user = user;
        this.amountUntil2.setText(amountUntil2);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiquidacionJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiquidacionJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiquidacionJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiquidacionJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiquidacionJFrame().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        typeLiquidacion = new javax.swing.JComboBox<>();
        liquidar = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        amountUntil2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Liquidación Automática");

        jLabel1.setText("Tipo de liquidación");

        liquidar.setText("Liquidar");
        liquidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liquidarActionPerformed(evt);
            }
        });

        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel3.setText("<html><p style=\"font-weight: bold;text-decoration:underline\">Pasos previos comunes:</p></html>");
        jLabel3.setToolTipText("");

        jLabel2.setText("1) Verificar el periodo, el año y el número de listado del grupo");

        jLabel4.setText("2) Verificar que el expediente indicado sea correcto");

        jLabel7.setText("Monto máximo de retención al 2%:");

        amountUntil2.setToolTipText("");

        jLabel9.setText("<html><p style=\"font-weight: bold;text-decoration:underline\">Pasos previos Contratos:</p></html>");
        jLabel9.setToolTipText("");

        jLabel12.setText("1) Completar la situación de AFIP de cada contratado (AC, EX, NA o RI)");

        jLabel13.setText("2) Verificar datos del tipo, letra, fecha y monto  del comprobante");

        jLabel14.setText("3) En caso de ser necesario, modificar el importe de retención al 2%");

        jLabel10.setText("3) De existir registros liquidados, completar la columna OP con los datos de Pilagá");

        jLabel11.setText("4) Indicar si el grupo ya fue creado.En este caso, se asume que se liquidaron todos");

        jLabel15.setText("    los registros y los mismos ya se encuentran incluidos en el grupo en Nivel 4");

        jLabel16.setText("4) Control de totales del grupo en nivel 4");
        jLabel16.setEnabled(false);

        jLabel17.setText("<html><p style=\"font-weight: bold;text-decoration:underline\">Orden de ejecución del programa:</p></html>");
        jLabel17.setToolTipText("");

        jLabel19.setText("1) Lectura del archivo");
        jLabel19.setEnabled(false);

        jLabel20.setText("2) Liquidacion de registros");
        jLabel20.setEnabled(false);

        jLabel21.setText("3) Creación del grupo e inclusión de las liquidaciones");
        jLabel21.setEnabled(false);

        jLabel22.setText("7) Pase a nivel 7 por grupo");
        jLabel22.setEnabled(false);

        jLabel23.setText("6) Retención de impuesto (Contratos)");
        jLabel23.setEnabled(false);

        jLabel24.setText("5) Detección de diferencias");
        jLabel24.setEnabled(false);

        jLabel25.setText("8) Control de totales del grupo en nivel 7");
        jLabel25.setEnabled(false);

        jCheckBox1.setText("Grupo creado");

        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("+ INFO");
        jLabel5.setToolTipText("<html>\n<ul>\n<li>Completar con el importe hasta el cuál se retendrá 2%. Aquellos que superen el importe, se retendrán al 4%</li>\n<li>Dejar vacío o 0 (cero) para retener al 4%</li>\n<li>Para dejar un importe fijo, agregar el mismo a la primera línea del archivo <code>retenciones/importe_retencion_hasta_2%.txt</code></li>\n</ul>\n</html>");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setMaximumSize(new java.awt.Dimension(50, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(50, 25));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel10)
                                                                        .addComponent(jLabel11)
                                                                        .addComponent(jLabel15)
                                                                        .addComponent(jLabel12)
                                                                        .addComponent(jLabel13)
                                                                        .addComponent(jLabel14)
                                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                        .addComponent(jLabel7)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(amountUntil2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                                                                .addGap(70, 70, 70)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel19)
                                                                        .addComponent(jLabel20)
                                                                        .addComponent(jLabel21)
                                                                        .addComponent(jLabel16)
                                                                        .addComponent(jLabel24)
                                                                        .addComponent(jLabel23)
                                                                        .addComponent(jLabel25)
                                                                        .addComponent(jLabel22)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(typeLiquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jCheckBox1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(345, 345, 345)
                                                .addComponent(liquidar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(typeLiquidacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel7)
                                                .addComponent(amountUntil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel24)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel25)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(liquidar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private InputStream getExcelFile() {
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel Files", "xlsx", "xlsm");
        fc.setFileFilter(filter);
        int response = fc.showOpenDialog(this);
        if (response == JFileChooser.APPROVE_OPTION) {
            this.file = fc.getSelectedFile();
            this.directory = file.getParent();

            try {
                return new FileInputStream(file);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(LiquidacionJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return null;
    }

    private XSSFWorkbook getWorkbook() {
        InputStream file = getExcelFile();
        if (Objects.nonNull(file)) {
            try {
                return new XSSFWorkbook(file);
            } catch (IOException ex) {
                Logger.getLogger(LiquidacionJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return null;
    }

    private void liquidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liquidarActionPerformed

        this.jLabel19.setEnabled(true);
        Double amount2;

        try {
            amount2 = StringUtils.isNullOrEmpty(this.amountUntil2.getText()) ? null : Double.parseDouble(this.amountUntil2.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El formato indicado no es válido");
            return;
        }

        XSSFWorkbook workbook = getWorkbook();
        if (Objects.isNull(workbook)) {
            return;
        }

        JOptionPane.showMessageDialog(null, "Durante la ejecución, el programa escribirá en el archivo Excel seleccionado. Si el archivo se encuentra abierto por otro programa, los cambios no se reflejarán hasta que no se cierre el mismo");

        XSSFSheet sheet = workbook.getSheetAt(0);
        LiquidationType liquidationType = LiquidationType.fromDescription(this.typeLiquidacion.getSelectedItem().toString());

        if (Objects.isNull(liquidationType)) {
            JOptionPane.showMessageDialog(null, "El tipo de liquidación no es válido");
            return;
        }

        ExcelReader reader = liquidationType.getExcelReader();
        Browser browser = liquidationType.getBrowser();

        Group group = new Group();
        group.setGroupName(reader.getGroupName(sheet));
        group.setFile(reader.getExpediente(sheet));
        group.setTypeOP(browser.getTypeOp());
        group.setLiquidaciones(reader.getLiquidaciones(sheet));

        OperationWriter writer = new OperationWriter(group, directory);
        writer.writeFirstRead(group);

        Logger rootLogger = Logger.getLogger("");
        try {
            // Create a FileHandler to write logs to the specified file
            FileHandler fileHandler = new FileHandler(String.format("%s%soutput-%s.txt", directory, File.separator, group.getGroupName()), true); // Append mode
            fileHandler.setFormatter(new SimpleFormatter()); // Use a simple text format

            // Add the FileHandler to the root logger
            rootLogger.addHandler(fileHandler);

            // Optionally, remove the default console handler
            rootLogger.setUseParentHandlers(false);

            // Redirect System.out and System.err to the same file
            PrintStream fileOut = new PrintStream(new FileOutputStream(String.format("%s%soutput-%s.txt", directory, File.separator, group.getGroupName()), true));
            System.setOut(fileOut);
            System.setErr(fileOut);
            System.out.println("-----------------------------------------------------------------------");
            System.out.printf("Ejecución del programa: %s%n", LocalDateTime.now());
            System.out.printf("Configuración: %s%n", HtmlElement.INSTANCE.isLocal() ? "local" : "server");
        } catch (FileNotFoundException e) {
            System.out.println("Error opening file: " + e.getMessage());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        if (JOptionPane.showConfirmDialog(null,
                writeFirstReadConfirmation(group), "¿Continuar?", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_NO_OPTION) {
            return;
        }

        this.jLabel20.setEnabled(true);

        browser.open();
        browser.goToPilaga();
        browser.loginPilaga(user);
        browser.goToNew();
        try {
            browser.liquidate(group);
        } finally {
            reader.completeOP(group, workbook, file);
            writer.writeResultLiquidacion(group);
        }

        this.jLabel21.setEnabled(true);
        if (!this.jCheckBox1.isSelected()) {
            browser.createGroup(group);
        }

        this.jLabel16.setEnabled(true);
        group.setLiquidacionesARetener(group.getLiquidacionesLiquidadas());
        browser.goToLevel4GroupAuthorization();
        browser.filterGroup(group);
        if (!browser.sameTotal(group, '4')) {
            this.jLabel24.setEnabled(true);
            browser.differences(group);
            writer.writeExcludedLiquidations(group);
        }

        this.jLabel23.setEnabled(true);
        this.jLabel22.setEnabled(true);
        try {
            browser.authorizeLevel4(group, amount2);
        } finally {
            writer.writeLiquidacionNoRetenidas(group);
        }

        this.jLabel25.setEnabled(true);
        browser.goToLevel7GroupAuthorization();
        browser.filterGroup(group);
        if (!browser.sameTotal(group, '7')) {
            JOptionPane.showMessageDialog(null, "Revisar diferencias");
        }
        browser.goToLiquidationsList(group);
        writer.writeForExp(group);
        writer.writeInstrucciones();
        JOptionPane.showMessageDialog(null, "CONSULTAR EL ARCHIVO CON LOS RESULTADOS DE LA LIQUIDACIÓN\n\nDescargar OP y unirlas en un único archivo.");

        writer.closeWriters();
    }

    private String writeFirstReadConfirmation(Group group) {

        StringBuilder sb = new StringBuilder();

        sb.append("Resumen de las liquidaciones a realizar...\n");
        sb.append("Nombre del grupo: " + group.getGroupName()
                + "\nExpediente: " + group.getFile().toString());
        for (Liquidation li : group.getLiquidaciones()) {
            sb.append(li.getMessage());
        }
        sb.append("\nTotal: ");
        sb.append(Utils.toCurrencyFormat(group.getTotalAmount()));

        return sb.toString();
    }
}
